# Generated by Django 4.1.3 on 2022-11-13 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InstaApp', '0004_alter_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reels', models.FileField(upload_to='reels')),
                ('likes', models.ManyToManyField(blank='True', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
