# Generated by Django 4.1.3 on 2022-11-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaApp', '0005_reels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reels',
            name='reels',
        ),
        migrations.AddField(
            model_name='reels',
            name='reel',
            field=models.FileField(blank='True', upload_to='reel'),
        ),
    ]
