# Generated by Django 4.1.3 on 2022-11-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstaApp', '0006_remove_reels_reels_reels_reel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ImageField(upload_to='story')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InstaApp.profile')),
            ],
        ),
    ]
