# Generated by Django 4.1.3 on 2022-11-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaApp', '0008_alter_post_image_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='profilepics'),
        ),
    ]
